### ISSUE TITLE
Only Perform CI-CD builds/releases on the main branch

### ISSUE THREAD

**Issue by shiva-hack** [filecoin-project/filecoin-station#13] opened 2022-03-10 13:28 UTC
Currently, the CICD builds on any branch that we push the code to. this may lead to unwanted code being published.

**Comment by patrickwoodhead** [comment] 2022-03-10 15:54
We can fix this using https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore

@lidel which branches do we need the ci.yml to run on?

**Comment by lidel** [comment] 2022-04-03 18:26
@shiva-hack mind elaborating? 
- what is the threat model you have in mind?
- how "unwanted code" could be published, step by step?

My understanding is that:
* nothing is published to github releases automatically 
  *  when a tag is built, CI will create a release draft ([code](https://github.com/filecoin-project/filecoin-station/blob/main/.github/workflows/ci.yml#L103)) and attach built artifacts to it , but it is up to a human maintainer to make a decision when/if to publish it
  * signing requires secrets which are exposed only on branch builds, and disabled on PRs from forks 
    * allows external contributors to benefit from any tests, without producing malicious executables that look official
    * we atatch build artifacts to CI job output to make it easier to test, these binaries are not official, and get deleted after ~90 days (only thing we care are official artifacts attached to github release)

**Comment by bajtos** [comment] 2022-05-26 14:36
@lidel I'd like to resume the discussion about when to build Electron binaries.

At the moment, when I open a pull request, the CI process is building Electron binaries and trying to attach them to a GH Release.

Action run: https://github.com/filecoin-project/filecoin-station/actions/runs/2391190626

What happens:
- The step "get tag" fails: `Error: Not a tag ref (refs/pull/26/merge)`
- The binary name is using the last released version (0.0.6 in my case). Example file name: `Filecoin Station-0.0.6.dmg`
- The step "Attach produced packages to Github Action" seems to complete successfully.

However, when I inspect the [GitHub Release 0.0.6](https://github.com/filecoin-project/filecoin-station/releases/tag/v0.0.6), I see that all binaries were uploaded on 04 Mar 2022 and haven't been changed since then. (Which is a good thing!)

I find this rather confusing:
- Where did we attached the packages to?
- Why are we wasting CPU cycles and slowing down the CI process with building app packages that are discarded?

I am proposing to modify GitHub Actions triggers to run the "package" workflow only for git tags.

Any objections?

**Comment by lidel** [comment] 2022-05-26 16:08
>  Where did we attach the packages?

PR artifacts are attached to the build's Summary page. These unofficial dev builds are persisted by GitHub for 90days.

Example: https://github.com/filecoin-project/filecoin-station/actions/runs/2391190626
![2022-05-26_17-38](https://user-images.githubusercontent.com/157609/170522785-a9f298d2-97ca-4e31-94a2-01028dc32142.png)


> Why are we wasting CPU cycles and slowing down the CI process with building app packages that are discarded?

- Main reason: this is the only way to confirm everything works and Electron app builds correctly. 
  - Every piece of the pipeline is brittle and untrustworthy. Electron, electro-builder, github action's runtime for macOS and Windows, we had bugs in each. In IPFS Desktop we had situations where master stopped building artifacts after "green"  PR was merged (without running a real build). 

- Second reason: makes it easier for other team members to download and test a specific change. 
   - `electron .` does not fully reproduce the behavior of the final package, and building locally is takes time
    - if you don't test the final artifact, you may merge code that behaves differently than the local `electron .` run

> I am proposing to modify GitHub Actions triggers to run the "package" workflow only for git tags.
> Any objections?

- I suggest keeping it, and if you don't want long PR builds, then keep so it runs on each merge  to master,  so you are not surprised during the release day :)
  - If you are building only on tags (release day) you will be running blind 99% of time, unaware that the package build on specific platform, macOS/Windows singing or macOS notarization is broken. Then you will be scrambling around to fix things under time pressure to unblock the release, instead of doing it calmly as part of regular maintenance work.

**Comment by gruns** [comment] 2022-05-26 22:45
> I am proposing to modify GitHub Actions triggers to run the "package" workflow only for git tags.

👍 here insofar that is how a commit is deployed to production elsewhere in saturn: this is exactly what we're going to do with the l1 and orchestrator (cc'ing @DiegoRBaquero)

* on every commit, tagged or not, the l1 (https://github.com/filecoin-project/saturn-node) and orchestrator (https://github.com/filecoin-project/saturn-orchestrator) execute CI/CD and that commit is automatically deployed to test net (all l1s have auto updates turned on by default and we control the orchestrator)

* on every *tagged* commit, the l1 and orchestrator execute CI/CD and that commit is automatically deployed to main net (all l1s have auto updates turned on by default and we control the orchestrator)

so for consistency and adhering the principle of least surprise, the action that controls how to deploy a new production version should be the same across our projects: push a tagged commit


as for triggering an electron build on every commit, this

> Main reason: this is the only way to confirm everything works and Electron app builds correctly.

seems a good reason 🙂

**Comment by bajtos** [comment] 2022-05-30 10:43
> PR artifacts are attached to the build's Summary page. These unofficial dev builds are persisted by GitHub for 90days.

Very cool! I learned something new today💡

> Main reason: this is the only way to confirm everything works and Electron app builds correctly.

Makes perfect sense 👍🏻 

> the action that controls how to deploy a new production version should be the same across our projects: push a tagged commit

+1

Let's close this issue as resolved/not-planned then.

**Closed by bajtos** 2022-05-30 10:43 UTC
